---
- name: Include theme variables
  include_vars: "themes/{{theme}}.yml"
  when: theme is defined

- name: Render template files
  template:
    src: "{{ item['src'] }}"
    dest: "{{ item['dest'] }}"
  with_items:
    - src: bashrc.j2
      dest: ~/.bashrc
    - src: bash_profile.j2
      dest: ~/.bash_profile
    - src: Xdefaults.j2
      dest: ~/.Xdefaults
    - src: bg-saved.cfg.j2
      dest: ~/.config/nitrogen/bg-saved.cfg
    - src: nitrogen.cfg.j2
      dest: ~/.config/nitrogen/nitrogen.cfg
    - src: i3config.j2
      dest: ~/.i3/config
    - src: i3blocks.conf.j2
      dest: ~/.i3blocks.conf
#    - src: i3status.conf.j2
#      dest: ~/.i3status.conf


- name: Source bashrc
  shell: ". ~/.bashrc"

- name: Reload the desktop
  shell: "reload-desktop"
