---
- name: Probe OS type
  hosts: localhost
  connection: local
  tasks:
    - group_by: key="os_{{ ansible_distribution }}"

- name: OS specific dependencies
  hosts: os_Archlinux
  become: yes
  tasks:
    # - name: Update pacman

    - name: Install move in dependencies
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        - i3-wm
#        - i3blocks   - needs yaourt - how do?
#        - mu
        - zsh
        - zsh-completions
        - zsh-syntax-highlighting
        - noto-fonts
        - noto-fonts-emoji
        - emacs
        - nitrogen
        - git
        - rofi

- name: OS specific dependencies
  hosts: os_Ubuntu
  become: yes
  tasks:
    # - name: Update pacman

    - name: Install move in dependencies
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - i3-wm
        - zsh
        - zsh-completions
        - zsh-syntax-highlighting
        - noto-fonts
        - noto-fonts-emoji
        - emacs
        - nitrogen
        - git
        - rofi


- name: Common configurations
  hosts: localhost
  connection: local
  roles:
    - role: git
      git_config:
        user:
          name: Christopher Kotfila
          email: chris.kotfila@kitware.com
        merge:
          conflictstyle: diff3
        rerere:
          enabled: true
        core:
          editor: "emacsclient -c"
          excludesfile: "~/.gitexcludesfile"
        status:
          submoduleSummary: true


- name: WM themes and backgrounds
  hosts: localhost
  connection: local
  roles:
    - role: wm
